image: docker:stable
stages:
  - test
  - publish

include:
  - project: 'cdb/openprocurement.documentservice.ci-configuration'
    file: '.gitlab-ci-private.yml'


test_python2:
  image: python:2.7-jessie
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt -e .[test]
  script:
    - py.test --cov=openprocurement.documentservice
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'

test_python3:
  extends: test_python2
  image: python:3.6-jessie
