language: python
sudo: required
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
env:
  global:
    - TZ=Europe/Kiev
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -e .[test]
script:
  - py.test --cov=openprocurement.documentservice
after_success:
  - coveralls
