version: '3'
services:
  ds:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6543:6543"
#    command: "sleep infinity"
    volumes:
      - "./openprocurement:/app/openprocurement:delegated"
      - "./setup.py:/app/setup.py:delegated"
      - "./config:/app/config:delegated"
