GET /get/a1fdbe104e054212a53a29539dac1927?KeyID=70f4a580&Expires=1557317176&Signature=%2FrCXYPk0snfgOMd603FD000l7JNop3r4NeoquekeVqUpg6e0uQjtcQo%2FShdzrlFl1ujjJjA4GCj8qILtqVe%252BBA%253D%253D HTTP/1.0
Host: upload-docs-sandbox.prozorro.gov.ua


200 OK
Content-Disposition: attachment; filename=file.txt
Content-Type: text/plain; charset=UTF-8


