POST /register HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 58
Content-Type: application/json
Host: upload-docs-sandbox.prozorro.gov.ua

{
  "data": {
    "hash": "md5:9a0364b9e99bb480dd25e1f0284c8555"
  }
}


201 Created
Content-Type: application/json
Location: http://upload-docs-sandbox.prozorro.gov.ua/upload/1a6a1d8916ed4436bc25aac181ddc098?KeyID=70f4a580&Signature=14XVsS%2FJSm%252BylBvSPU98%252BBhqVNP%2F8dkZq2C6GfJJ5ZYqP61kgP57y7KuWg6sasv54lzhZr1lQMVgepdEG%2FDxCg%253D%253D

{
  "upload_url": "http://upload-docs-sandbox.prozorro.gov.ua/upload/1a6a1d8916ed4436bc25aac181ddc098?KeyID=70f4a580&Signature=14XVsS%2FJSm%252BylBvSPU98%252BBhqVNP%2F8dkZq2C6GfJJ5ZYqP61kgP57y7KuWg6sasv54lzhZr1lQMVgepdEG%2FDxCg%253D%253D", 
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1a6a1d8916ed4436bc25aac181ddc098?KeyID=70f4a580&Signature=t79zzRLES%2F5dqd54Z%252B9DOHlUrIGsZSL9qNhQJUZ0ws0CLTxPq4M5E7q0%2FY1xmlyhH%252BBYdsDLVvpJ4u6ajZjzAw%253D%253D", 
    "hash": "md5:9a0364b9e99bb480dd25e1f0284c8555"
  }
}

