POST /upload/a1fdbe104e054212a53a29539dac1927?KeyID=70f4a580&Signature=KvnX8x3EmwDj1WR17o18BrTS9FGZZx8zcn8yDlAWuwsYqLRaAkalPI%252BXtz05e9Qf5Dz1fvnpoRX6Xkeao2NpCA%253D%253D HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 179
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy188876221254$
Host: upload-docs-sandbox.prozorro.gov.ua

------------a_BoUnDaRy188876221254$
Content-Disposition: form-data; name="file"; filename="file.txt"
Content-Type: text/plain

content
------------a_BoUnDaRy188876221254$--



200 OK
Content-Type: application/json

{
  "get_url": "http://public-docs-sandbox.prozorro.gov.ua/get/a1fdbe104e054212a53a29539dac1927?KeyID=70f4a580&Expires=1557317176&Signature=%2FrCXYPk0snfgOMd603FD000l7JNop3r4NeoquekeVqUpg6e0uQjtcQo%2FShdzrlFl1ujjJjA4GCj8qILtqVe%252BBA%253D%253D", 
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a1fdbe104e054212a53a29539dac1927?KeyID=70f4a580&Signature=g4MEkUGomA7Uwb7anw%252BCJTnhsrNPBsMKKUgybfQ72e7sIFx9%252BxPYukyJIsk%252B%2Fgw9kbqvMy6CLVQDKSltGjHECA%253D%253D", 
    "format": "text/plain", 
    "hash": "md5:9a0364b9e99bb480dd25e1f0284c8555", 
    "title": "file.txt"
  }
}

